export type LabAnalyteDef = {
  key: string;
  label: string;
  unit: string;
  min: number;
  max: number;
  /** Faixa ampla só para OCR — não define normalidade */
  plausibleMin: number;
  plausibleMax: number;
  /** Padrões para localizar no texto do laudo */
  patterns: RegExp[];
};

export const LAB_ANALYTES: LabAnalyteDef[] = [
  {
    key: "hemoglobina",
    label: "Hemoglobina",
    unit: "g/dL",
    min: 12,
    max: 16,
    plausibleMin: 4,
    plausibleMax: 22,
    patterns: [/\bhb\b/i, /hemoglob/i],
  },
  {
    key: "leucocitos",
    label: "Leucócitos",
    unit: "/mm³",
    min: 4000,
    max: 11000,
    plausibleMin: 500,
    plausibleMax: 100000,
    patterns: [/leuc[oó]cit/i, /\bwbc\b/i],
  },
  {
    key: "plaquetas",
    label: "Plaquetas",
    unit: "/mm³",
    min: 150000,
    max: 450000,
    plausibleMin: 10000,
    plausibleMax: 1000000,
    patterns: [/plaqueta/i, /\bplt\b/i],
  },
  {
    key: "sodio",
    label: "Sódio",
    unit: "mEq/L",
    min: 135,
    max: 145,
    plausibleMin: 110,
    plausibleMax: 180,
    patterns: [/\bna\+?\b/i, /s[oó]dio/i],
  },
  {
    key: "potassio",
    label: "Potássio",
    unit: "mEq/L",
    min: 3.5,
    max: 5.5,
    plausibleMin: 2,
    plausibleMax: 8,
    patterns: [/\bk\+?\b/i, /pot[aá]ssio/i],
  },
  {
    key: "creatinina",
    label: "Creatinina",
    unit: "mg/dL",
    min: 0.6,
    max: 1.2,
    plausibleMin: 0.1,
    plausibleMax: 15,
    patterns: [/creatinin/i, /\bcr\b/i],
  },
  {
    key: "ureia",
    label: "Ureia",
    unit: "mg/dL",
    min: 15,
    max: 45,
    plausibleMin: 5,
    plausibleMax: 300,
    patterns: [/ureia/i, /\bbun\b/i],
  },
  {
    key: "pcr",
    label: "PCR",
    unit: "mg/L",
    min: 0,
    max: 5,
    plausibleMin: 0,
    plausibleMax: 500,
    patterns: [/\bpcr\b/i, /prote[ií]na c reativa/i],
  },
  {
    key: "lactato",
    label: "Lactato",
    unit: "mmol/L",
    min: 0.5,
    max: 2.2,
    plausibleMin: 0.1,
    plausibleMax: 20,
    patterns: [/lactat/i, /\blac\b/i],
  },
  {
    key: "glicemia",
    label: "Glicemia",
    unit: "mg/dL",
    min: 70,
    max: 99,
    plausibleMin: 20,
    plausibleMax: 800,
    patterns: [/glicemia/i, /glicose/i, /\bhgt\b/i, /glucose/i],
  },
  {
    key: "bilirrubina_total",
    label: "Bilirrubina Total",
    unit: "mg/dL",
    min: 0.3,
    max: 1.2,
    plausibleMin: 0,
    plausibleMax: 30,
    patterns: [/bilirrubina total/i, /\bbt\b/i],
  },
  {
    key: "bilirrubina_direta",
    label: "Bilirrubina Direta",
    unit: "mg/dL",
    min: 0,
    max: 0.3,
    plausibleMin: 0,
    plausibleMax: 20,
    patterns: [/bilirrubina direta/i, /\bbd\b/i],
  },
  {
    key: "tgo",
    label: "TGO/AST",
    unit: "U/L",
    min: 5,
    max: 40,
    plausibleMin: 1,
    plausibleMax: 5000,
    patterns: [/\btgo\b/i, /\bast\b/i],
  },
  {
    key: "tgp",
    label: "TGP/ALT",
    unit: "U/L",
    min: 7,
    max: 56,
    plausibleMin: 1,
    plausibleMax: 5000,
    patterns: [/\btgp\b/i, /\balt\b/i],
  },
  {
    key: "rni",
    label: "RNI",
    unit: "",
    min: 0.8,
    max: 1.2,
    plausibleMin: 0.5,
    plausibleMax: 10,
    patterns: [/\brni\b/i, /\binr\b/i],
  },
  {
    key: "amilase",
    label: "Amilase",
    unit: "U/L",
    min: 28,
    max: 100,
    plausibleMin: 10,
    plausibleMax: 5000,
    patterns: [/amilase/i],
  },
  {
    key: "lipase",
    label: "Lipase",
    unit: "U/L",
    min: 13,
    max: 60,
    plausibleMin: 5,
    plausibleMax: 5000,
    patterns: [/lipase/i],
  },
  {
    key: "calcio",
    label: "Cálcio",
    unit: "mg/dL",
    min: 8.5,
    max: 10.5,
    plausibleMin: 5,
    plausibleMax: 15,
    patterns: [/c[aá]lcio/i, /\bca\b/i],
  },
  {
    key: "magnesio",
    label: "Magnésio",
    unit: "mg/dL",
    min: 1.6,
    max: 2.6,
    plausibleMin: 0.5,
    plausibleMax: 5,
    patterns: [/magn[eé]sio/i, /\bmg\b/i],
  },
  {
    key: "fosforo",
    label: "Fósforo",
    unit: "mg/dL",
    min: 2.5,
    max: 4.5,
    plausibleMin: 1,
    plausibleMax: 10,
    patterns: [/f[oó]sforo/i],
  },
  {
    key: "albumina",
    label: "Albumina",
    unit: "g/dL",
    min: 3.5,
    max: 5.0,
    plausibleMin: 1,
    plausibleMax: 6,
    patterns: [/albumina/i],
  },
  {
    key: "tsh",
    label: "TSH",
    unit: "mUI/L",
    min: 0.4,
    max: 4.0,
    plausibleMin: 0.01,
    plausibleMax: 100,
    patterns: [/\btsh\b/i],
  },
];

export const LAB_ANALYTE_MAP = new Map(
  LAB_ANALYTES.map((a) => [a.key, a]),
);

export function getAnalyte(key: string): LabAnalyteDef | undefined {
  return LAB_ANALYTE_MAP.get(key);
}
